export const CHANGE_CATEGORY_GOODS_COUNT = "changeCategoryCount"
export const CHANGE_CATEGORY_GOODS_SALE = "changeCategoryGoodsSale"
export const CHANGE_CATEGORY_GOODS_FAVOR = "changeCategoryGoodsFavor"
export const CHANGE_ADDRESS_GOODS_SALE = "changeAddressSale"
export const CHANGE_GOODS_AMOUNT_LIST = "changeGoodsAmountList"
